FROM docker.io/kalilinux/kali-rolling

ENV SHELL=/bin/bash
ENV LANG=en_US.UTF-8

COPY ./config/bashrc /root/.bashrc
COPY ./config/aliases /root/.bash_aliases
COPY ./config/inputrc /etc/inputrc

COPY extra-packages /

# install packages
RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        flatpak-xdg-utils \
        $(cat extra-packages | xargs) && \
    rm -rd /var/lib/apt/lists/*

RUN rm /extra-packages

# Fix empty bind-mount to clear selinuxfs (see #337)
RUN mkdir /usr/share/empty

# Add flatpak-spawn to /usr/bin
RUN ln -s /usr/libexec/flatpak-xdg-utils/flatpak-spawn /usr/bin/

WORKDIR /opt

# Pip2
RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python2 get-pip.py

# Pip install
RUN python3 -m pip install mitm6 service_identity

## Git Tools
#RUN mkdir /root/.ssh/ && touch /root/.ssh/known_hosts
RUN touch /root/.ssh/known_hosts
### Add host keys
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN git clone https://github.com/SySS-Research/Seth
RUN git clone https://github.com/bonsaiviking/NfSpy
RUN git clone https://github.com/fox-it/cve-2019-1040-scanner
RUN git clone https://github.com/dirkjanm/adidnsdump
RUN git clone https://github.com/dirkjanm/privexchange/
RUN git clone https://github.com/lgandx/PCredz
RUN git clone https://github.com/dirkjanm/krbrelayx/
RUN git clone https://github.com/topotam/PetitPotam
RUN git clone https://github.com/Wh04m1001/DFSCoerce
RUN git clone https://github.com/ShutdownRepo/ShadowCoerce
RUN git clone https://github.com/dirkjanm/PKINITtools
RUN git clone https://github.com/p0dalirius/Coercer
RUN git clone https://github.com/zyn3rgy/LdapRelayScan
RUN git clone https://github.com/eldraco/Sapito
RUN git clone https://github.com/joaomatosf/jexboss
RUN git clone https://github.com/gremwell/o365enum
RUN git clone https://github.com/openwall/john -b bleeding-jumbo john 
RUN git clone https://github.com/AlmondOffSec/PassTheCert.git
RUN git clone https://github.com/CravateRouge/bloodyAD.git 

#WORKDIR /opt/inf/PCredz
RUN apt-get update && apt-get install -y libpcap-dev && python3 -m pip install Cython && python3 -m pip install python-libpcap

WORKDIR /opt/LdapRelayScan
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/PKINITtools
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/Sapito
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/Coercer
RUN python3 setup.py install

WORKDIR /opt/adidnsdump
RUN python3 -m pip install .

WORKDIR /opt/Seth
RUN apt-get install -y openssl iptables && python3 -m pip install -r requirements.txt

WORKDIR /opt/NfSpy
RUN python2 setup.py install

WORKDIR /opt/jexboss
RUN python3 -m pip install -r requires.txt

WORKDIR /opt/john/src
RUN ./configure && make -s clean && make -sj4 

WORKDIR /opt
RUN wget https://hashcat.net/files/hashcat-6.2.6.7z && 7za x hashcat-6.2.6.7z

WORKDIR /opt/bloodyAD/
RUN python3 -m pip install .

## Binaries
RUN wget https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
RUN wget https://github.com/ropnop/go-windapsearch/releases/download/v0.3.0/windapsearch-linux-amd64
RUN wget https://github.com/OJ/gobuster/releases/download/v3.0.1/gobuster-linux-amd64.7z
RUN wget https://github.com/sensepost/gowitness/releases/download/2.4.2/gowitness-2.4.2-linux-amd64
RUN wget https://github.com/hdm/nextnet/releases/download/v0.0.2/nextnet_0.0.2_linux_amd64.tar.gz
RUN wget https://github.com/liamg/traitor/releases/download/v0.0.14/traitor-amd64
RUN wget https://github.com/lkarlslund/ldapnomnom/releases/download/v1.0.7/ldapnomnom-linux-amd64

RUN wget https://github.com/jpillora/chisel/releases/download/v1.8.1/chisel_1.8.1_linux_386.gz
RUN wget https://github.com/jpillora/chisel/releases/download/v1.8.1/chisel_1.8.1_linux_amd64.gz
RUN wget https://github.com/jpillora/chisel/releases/download/v1.8.1/chisel_1.8.1_windows_386.gz
RUN wget https://github.com/jpillora/chisel/releases/download/v1.8.1/chisel_1.8.1_windows_amd64.gz

## Ruby Tools
RUN gem install haiti-hash

CMD /bin/bash
