## Kali
FROM kalilinux/kali-rolling

ENV SHELL=/bin/bash
ENV LANG=en_US.UTF-8i

COPY ./config/.bashrc /root/.bashrc
COPY ./config/.bash_aliases /root/.bash_aliases
COPY ./config/inputrc /etc/inputrc

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 \
    python3-pip \
    python2 \
    responder \
    dnsrecon \
    cewl \
    dsniff \
    enum4linux \
    iproute2 \
    driftnet \
    arp-scan \
    thc-ipv6 \
    thc-pptp-bruter \
    enum4linux \
    rpcbind \
    hydra \
    vim \
    spray \
    rsh-client \
    rusers \
    rwho \
    nbtscan-unixwiz \
    ncat \
    finger \
    davtest
    
RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ike-scan \
    ldapscripts \
    open-iscsi \
    proxychains4 \
    smbmap \
    snmp \
    snmp-mibs-downloader \
    winexe \
    wmis \
    yersinia \
    tcpdump \
    nmap \
    curl \
    apt-utils \
    changeme \
    wfuzz \
    dirb \
    gobuster \
    sipcalc \
    screen 

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    metasploit-framework \
    git \
    crackmapexec \
    python3-ldapdomaindump \
    python3-impacket \
    impacket-scripts \
    python3-lsassy \
    eyewitness \
    iputils-ping \
    nfs-common \
    powershell \
    telnet \
    dnsutils \
    heimdal-clients \
    sqlmap \
    ffuf \
    unicorn-magic \
    amass \
    wget \
    exploitdb \
    pwncat 

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    powercat \
    powersploit \
    nishang \
    rlwrap \
    windows-binaries \
    default-mysql-client \
    medusa \
    dnschef \
    passing-the-hash \
    ridenum \
    hashid \
    sshuttle \
    dos2unix \
    openssh-server \
    libimage-exiftool-perl \
    mingw-w64 \
    mono-devel \
    powershell-empire \
    binwalk \
    sslscan \
    nikto \
    openjdk-17-jre \
    rsync \
    crowbar \
    tnscmd10g \
    tnftp \
    ftp-ssl \
    tftp \
    theharvester \
    netdiscover

WORKDIR /opt

# Pip2
RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python2 get-pip.py

# Pip install
RUN python3 -m pip install mitm6 service_identity
RUN python3 -m pip install witnessme

## Git Tools
#RUN mkdir /root/.ssh/ && touch /root/.ssh/known_hosts
RUN touch /root/.ssh/known_hosts
### Add host keys
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts


RUN git clone https://github.com/threat9/routersploit
RUN git clone https://github.com/SySS-Research/Seth
RUN git clone https://github.com/bonsaiviking/NfSpy
RUN git clone https://github.com/fox-it/cve-2019-1040-scanner
RUN git clone https://github.com/dirkjanm/adidnsdump
RUN git clone https://github.com/dirkjanm/privexchange/
RUN git clone https://github.com/lgandx/PCredz
RUN git clone https://github.com/dirkjanm/krbrelayx/
RUN git clone https://github.com/topotam/PetitPotam
RUN git clone https://github.com/Wh04m1001/DFSCoerce
RUN git clone https://github.com/ShutdownRepo/ShadowCoerce
RUN git clone https://github.com/dirkjanm/PKINITtools
RUN git clone https://github.com/ly4k/Certipy
RUN git clone https://github.com/p0dalirius/Coercer
RUN git clone https://github.com/zyn3rgy/LdapRelayScan
RUN git clone https://github.com/eldraco/Sapito
RUN git clone https://github.com/joaomatosf/jexboss
RUN git clone https://github.com/gremwell/o365enum.git

#WORKDIR /opt/inf/PCredz
RUN apt-get install -y libpcap-dev && python3 -m pip install Cython && python3 -m pip install python-libpcap

WORKDIR /opt/LdapRelayScan
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/PKINITtools
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/Sapito
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/Certipy
RUN python3 setup.py install

WORKDIR /opt/Coercer
RUN python3 setup.py install

WORKDIR /opt/adidnsdump
RUN python3 -m pip install .

WORKDIR /opt/routersploit
RUN python3 -m pip install -r requirements.txt

WORKDIR /opt/Seth
RUN apt-get install -y openssl iptables && python3 -m pip install -r requirements.txt

WORKDIR /opt/NfSpy
RUN python2 setup.py install

WORKDIR /opt/jexboss
RUN python3 -m pip install -r requires.txt

WORKDIR /opt/
## Binaries
RUN wget https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
RUN wget https://github.com/ropnop/go-windapsearch/releases/download/v0.3.0/windapsearch-linux-amd64
RUN wget https://github.com/OJ/gobuster/releases/download/v3.0.1/gobuster-linux-amd64.7z
RUN wget https://github.com/sensepost/gowitness/releases/download/2.2.0/gowitness-2.2.0-linux-amd64
RUN wget https://github.com/hdm/nextnet/releases/download/v0.0.2/nextnet_0.0.2_linux_amd64.tar.gz
RUN wget https://github.com/liamg/traitor/releases/download/v0.0.14/traitor-amd64

RUN wget https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_linux_386.gz
RUN wget https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_linux_amd64.gz
RUN wget https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_windows_386.gz
RUN wget https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_windows_amd64.gz

## Ruby Tools
RUN gem install haiti-hash
RUN gem install evil-winrm

CMD /bin/bash
