FROM kalilinux/kali-rolling

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
	powershell-empire \
	starkiller

ENTRYPOINT ["powershell-empire","-h"]
